### ISSUE TITLE
Install on Ubuntu

### ISSUE THREAD

**Issue by thecarl0s** [s3rj1k/nginx-js-challenge#2]
How do I install? which commands. I would be grateful, because I didn't understand very well

**Comment by s3rj1k** [comment]
@thecarl0s, you need to build deb package first, then just install with `dpkg -i`

**Comment by thecarl0s** [comment]
I use dpkg -i on which file?

**Comment by s3rj1k** [comment]
@thecarl0s on resulting *.deb file

[There Can Be Only One](https://www.youtube.com/watch?v=sqcLjcSloXs)
